### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by pmaier1** [owncloud/files_texteditor#210]
QA 
- [x] create release branch ? or just put a v2.2.1 tag at the head of current master?
- [x] bump version to 2.2.1 #211 
- [x] create testplan and test cases Link: #209 
- [x] test and document in testplan. Final release "Go"

Marketing

No time now

Build
- [x] makefile for the app ?
- [x] Add changelog if possible in time #208 #212
- [x] sign and build tarball
- [x] upload to marketplace
- [x] rename QA milestone to version number and close it

**Comment by pmaier1** [comment]
Just saw that there already is a changelog :+1: is it up-to-date?

**Comment by phil-davis** [comment]
Changelog is good.
#211 and #212 for approval and merge. then someone with more god-like powers can do adding version tag to the repo and make tarball...
